
# tap repositories and their packages

tap homebrew/core
brew antibody
brew archey
brew aspell
brew augeas
brew autoconf
brew bash
brew bat
brew boost
brew bwctl
brew bzip2
brew cairo
brew cheat
brew chezmoi
brew cmake
brew curl
brew direnv
brew dmg2img
brew doctl
brew dust
brew exa
brew faac
brew fd
brew fdk-aac
brew figlet
brew findutils
brew fontconfig
brew fping
brew freetype
brew fribidi
brew fselect
brew fx
brew gawk
brew gd
brew gdbm
brew geoip
brew gettext
brew gh
brew gist
brew git
brew git-lfs
brew git-secrets
brew glib
brew glib-networking
brew gmp
brew gnu-sed
brew gnutls
brew go
brew gobject-introspection
brew gotop
brew graphite2
brew graphviz
brew grv
brew gsettings-desktop-schemas
brew gts
brew gzip
brew harfbuzz
brew hopenpgp-tools
brew htop
brew httperf
brew httping
brew httpstat
brew hyperfine
brew icu4c
brew ilmbase
brew iperf3
brew iproute2mac
brew jasper
brew jid
brew jpeg
brew jq
brew json-c
brew krb5
brew lame
brew lftp
brew libav
brew libde265
brew libdnet
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libiconv
brew libidn
brew libidn2
brew libogg
brew libomp
brew libpng
brew libpq
brew libsodium
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libvorbis
brew libvpx
brew libyaml
brew libyubikey
brew libzip
brew little-cms2
brew locateme
brew lsusb
brew lua
brew lynis
brew lynx
brew lzo
brew m-cli
brew mas
brew maven
brew megatools
brew micro
brew mpfr
brew mtr
brew ncdu
brew ncftp
brew ncurses
brew net-snmp
brew netpbm
brew nettle
brew nikto
brew nmap
brew nnn
brew node
brew onefetch
brew oniguruma
brew openexr
brew openjdk
brew openjpeg
brew openssl@1.1
brew opus
brew p11-kit
brew p7zip
brew packer
brew pango
brew pcre
brew pcre2
brew peco
brew perl
brew pinentry-mac
brew pipx
brew pixman
brew pkg-config
brew pyenv
brew pyenv-virtualenv
brew python@3.8
brew ranger
brew rbenv
brew readline
brew redis
brew restic
brew ripgrep
brew rlwrap
brew rtmpdump
brew ruby
brew ruby-build
brew rust
brew rustup-init
brew s-lang
brew screen
brew sdl
brew shellcheck
brew shfmt
brew speedtest-cli
brew sqlite
brew ssllabs-scan
brew starship
brew stow
brew subnetcalc
brew tcl-tk
brew telnet
brew testssl
brew theora
brew tig
brew tin
brew tldr
brew tokei
brew trash
brew tree
brew unbound
brew webp
brew wget
brew wireguard-go
brew wireguard-tools
brew x264
brew x265
brew xvid
brew xz
brew ykpers
brew zip
brew zlib
brew zmap
brew zsh

tap homebrew/bundle

tap homebrew/cask-drivers
cask synology-drive
cask yubico-yubikey-manager
cask yubico-yubikey-personalization-gui
cask yubico-yubikey-piv-manager

tap homebrew/cask-fonts
cask font-3270-nerd-font
cask font-agave-nerd-font
cask font-anonymice-nerd-font
cask font-arimo-nerd-font
cask font-aurulent-sans-mono-nerd-font
cask font-awesome-terminal-fonts
cask font-bigblue-terminal-nerd-font
cask font-bitstream-vera-sans-mono-nerd-font
cask font-blex-mono-nerd-font
cask font-caskaydia-cove-nerd-font
cask font-code-new-roman-nerd-font
cask font-cousine-nerd-font
cask font-daddy-time-mono-nerd-font
cask font-dejavu-sans-mono-nerd-font
cask font-droid-sans-mono-nerd-font
cask font-fantasque-sans-mono-nerd-font
cask font-fira-code-nerd-font
cask font-fira-mono-nerd-font
cask font-fontawesome
cask font-go-mono-nerd-font
cask font-gohufont-nerd-font
cask font-hack-nerd-font
cask font-hackgen-nerd
cask font-hasklug-nerd-font
cask font-heavy-data-nerd-font
cask font-hurmit-nerd-font
cask font-im-writing-nerd-font
cask font-inconsolata-go-nerd-font
cask font-inconsolata-lgc-nerd-font
cask font-inconsolata-nerd-font
cask font-iosevka-nerd-font
cask font-jetbrains-mono-nerd-font
cask font-lekton-nerd-font
cask font-liberation-nerd-font
cask font-meslo-lg-nerd-font
cask font-monofur-nerd-font
cask font-monoid-nerd-font
cask font-mononoki-nerd-font
cask font-mplus-nerd-font
cask font-noto-nerd-font
cask font-open-dyslexic-nerd-font
cask font-overpass-nerd-font
cask font-profont-nerd-font
cask font-proggy-clean-tt-nerd-font
cask font-roboto-mono-nerd-font
cask font-sauce-code-pro-nerd-font
cask font-shure-tech-mono-nerd-font
cask font-space-mono-nerd-font
cask font-terminess-ttf-nerd-font
cask font-tinos-nerd-font
cask font-ubuntu-mono-nerd-font
cask font-ubuntu-nerd-font
cask font-victor-mono-nerd-font

tap homebrew/cask-versions

tap homebrew/services

tap homebrew/cask
cask 1password
cask adium
cask aerial
cask alfred
cask android-platform-tools
cask anki
cask appcleaner
cask artpip
cask atom
cask balenaetcher
cask bitbar
cask brooklyn
cask cheatsheet
cask cryptomator
cask cyberduck
cask dash
cask deepl
cask developerexcuses
cask discord
cask docker
cask dropbox
cask duet
cask epoch-flip-clock
cask firefox
cask flash-player
cask fliqlo
cask flux
cask go64
cask gpg-suite
cask iina
cask insomnia
cask iterm2
cask java
cask keybase
cask kindle
cask little-snitch
cask micro-snitch
cask netspot
cask notion
cask pocket-casts
cask podman
cask postman
cask punto-switcher
cask pycharm-ce
cask rocket
cask rq
cask rsyncosx
cask send-to-kindle
cask signal
cask slack
cask spectacle
cask spotify
cask sublime-text
cask telegram-desktop
cask the-unarchiver
cask transmission
cask tunnelblick
cask tutanota
cask vagrant
cask virtualbox
cask visual-studio-code
cask vlc
cask whatsapp
cask wire
cask wireshark
cask xnviewmp
cask zerotier-one

tap alehouse/unofficial

tap cjbassi/gotop

tap getantibody/tap

tap hudochenkov/sshpass
brew sshpass

tap jzelinskie/faq
brew faq

tap minio/stable

tap rcmdnk/file
brew brew-file

tap rs/tap
brew curlie

tap sambadevi/powerlevel9k

tap schollz/tap
brew croc

tap timothyye/tap

tap warrensbox/tap
brew tfswitch

tap zero-sh/tap
brew apply-user-defaults
brew zero

# Other Cask applications
cask font-3270-nerd-font-mono
cask font-anonymouspro-nerd-font
cask font-anonymouspro-nerd-font-mono
cask font-arimo-nerd-font-mono
cask font-bitstreamverasansmono-nerd-font-mono
cask font-codenewroman-nerd-font
cask font-codenewroman-nerd-font-mono
cask font-cousine-nerd-font-mono
cask font-dejavusansmono-nerd-font-mono
cask font-droidsansmono-nerd-font-mono
cask font-fantasquesansmono-nerd-font
cask font-fantasquesansmono-nerd-font-mono
cask font-firacode-nerd-font
cask font-firacode-nerd-font-mono
cask font-firamono-nerd-font
cask font-firamono-nerd-font-mono
cask font-go-mono-nerd-font-mono
cask font-gohu-nerd-font
cask font-gohu-nerd-font-mono
cask font-hack-nerd-font-mono
cask font-hasklig-nerd-font
cask font-hasklig-nerd-font-mono
cask font-heavydata-nerd-font-mono
cask font-hermit-nerd-font
cask font-hermit-nerd-font-mono
cask font-inconsolata-nerd-font-mono
cask font-inconsolatago-nerd-font-mono
cask font-inconsolatalgc-nerd-font-mono
cask font-iosevka-nerd-font-mono
cask font-jetbrainsmono-nerd-font
cask font-jetbrainsmono-nerd-font-mono
cask font-lekton-nerd-font-mono
cask font-liberationmono-nerd-font
cask font-liberationmono-nerd-font-mono
cask font-meslo-nerd-font
cask font-meslo-nerd-font-mono
cask font-monofur-nerd-font-mono
cask font-monoid-nerd-font-mono
cask font-mononoki-nerd-font-mono
cask font-mplus-1mn-nerd-mono
cask font-mplus-nerd-font-mono
cask font-noto-nerd-font-mono
cask font-profont-nerd-font-mono
cask font-proggyclean-nerd-font
cask font-proggyclean-nerd-font-mono
cask font-robotomono-nerd-font-mono
cask font-sharetechmono-nerd-font
cask font-sharetechmono-nerd-font-mono
cask font-sourcecodepro-nerd-font
cask font-sourcecodepro-nerd-font-mono
cask font-spacemono-nerd-font-mono
cask font-terminus-nerd-font
cask font-terminus-nerd-font-mono
cask font-tinos-nerd-font-mono
cask font-ubuntu-nerd-font-mono
cask font-ubuntumono-nerd-font-mono

# App Store applications
appstore 924726344 Deliveries (3.2.3)
appstore 975937182 Fantastical (3.1.4)
appstore 1351639930 Gifski (2.9.0)
appstore 639968404 Parcel (6.4)
appstore 1449412482 Reeder (4.2.5)
appstore 904280696 Things (3.12.5)
appstore 557168941 Tweetbot (2.5.8)
appstore 1482454543 Twitter (8.30)
