
# tap repositories and their packages

tap homebrew/core
brew antibody
brew aom
brew archey
brew aspell
brew augeas
brew autoconf
brew bandwhich
brew bash
brew bat
brew bettercap
brew bmon
brew boost
brew broot
brew bwctl
brew bzip2
brew cairo
brew cheat
brew chezmoi
brew cmake
brew confuse
brew curl
brew direnv
brew docbook
brew docbook-xsl
brew doctl
brew dos2unix
brew dust
brew e2fsprogs
brew exa
brew faac
brew fd
brew fdk-aac
brew figlet
brew findutils
brew flac
brew fontconfig
brew fping
brew freetype
brew fribidi
brew fselect
brew fx
brew fzf
brew gawk
brew gd
brew gdbm
brew geoip
brew gettext
brew gh
brew ghostscript
brew giflib
brew gist
brew git
brew git-delta
brew git-filter-repo
brew git-lfs
brew git-secrets
brew glances
brew glib
brew glib-networking
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnutls
brew go
brew gobject-introspection
brew gotop
brew graphite2
brew graphviz
brew grv
brew gsettings-desktop-schemas
brew gts
brew gzip
brew harfbuzz
brew hashcat
brew hcxtools
brew hopenpgp-tools
brew htop
brew httperf
brew httpie
brew httping
brew httpstat
brew hyperfine
brew icu4c
brew ilmbase
brew imagemagick
brew iperf3
brew iproute2mac
brew isl
brew jasper
brew jc
brew jid
brew jpeg
brew jq
brew json-c
brew krb5
brew lame
brew lazygit
brew leptonica
brew lf
brew lftp
brew libass
brew libav
brew libbluray
brew libde265
brew libdnet
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libheif
brew libiconv
brew libidn
brew libidn2
brew liblqr
brew libmpc
brew libogg
brew libomp
brew libpng
brew libpq
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvorbis
brew libvpx
brew libxml2
brew libyaml
brew libyubikey
brew libzip
brew little-cms2
brew locateme
brew lsd
brew lsusb
brew lua
brew lynis
brew lynx
brew lzo
brew m-cli
brew magic-wormhole
brew mas
brew maven
brew megatools
brew micro
brew mkcert
brew mpfr
brew mtr
brew mycli
brew mydumper
brew mysql-client
brew navi
brew ncdu
brew ncftp
brew ncurses
brew net-snmp
brew netpbm
brew nettle
brew nikto
brew nmap
brew nnn
brew node
brew onefetch
brew oniguruma
brew opencore-amr
brew openexr
brew openjdk
brew openjpeg
brew openssl@1.1
brew opus
brew p11-kit
brew p7zip
brew packer
brew pango
brew pcre
brew pcre2
brew peco
brew perl
brew pinentry-mac
brew pipx
brew pixman
brew pkg-config
brew procs
brew protobuf
brew pssh
brew pwgen
brew pyenv
brew pyenv-virtualenv
brew python@3.8
brew ranger
brew rargs
brew rbenv
brew readline
brew redis
brew restic
brew ripgrep
brew rlwrap
brew rtmpdump
brew rubberband
brew ruby
brew ruby-build
brew rust
brew rustup-init
brew s-lang
brew screen
brew screenresolution
brew sdl
brew sdl2
brew shared-mime-info
brew shellcheck
brew shfmt
brew sk
brew snappy
brew so
brew speedtest-cli
brew speex
brew sqlite
brew srt
brew ssh-audit
brew ssllabs-scan
brew sslyze
brew starship
brew stow
brew subnetcalc
brew tcl-tk
brew telnet
brew tesseract
brew testssl
brew tflint
brew theora
brew tig
brew tin
brew tldr
brew tokei
brew trash
brew tree
brew unbound
brew vim
brew watch
brew webp
brew wget
brew wimlib
brew wireguard-go
brew wireguard-tools
brew x264
brew x265
brew xmlto
brew xvid
brew xz
brew ykpers
brew youtube-dl
brew zenith
brew zip
brew zlib
brew zmap
brew zsh

tap homebrew/bundle

tap homebrew/cask-drivers
cask synology-drive
cask yubico-yubikey-manager
cask yubico-yubikey-personalization-gui
cask yubico-yubikey-piv-manager

tap homebrew/cask-fonts
cask font-3270-nerd-font
cask font-agave-nerd-font
cask font-anonymice-nerd-font
cask font-arimo-nerd-font
cask font-aurulent-sans-mono-nerd-font
cask font-awesome-terminal-fonts
cask font-bigblue-terminal-nerd-font
cask font-bitstream-vera-sans-mono-nerd-font
cask font-blex-mono-nerd-font
cask font-caskaydia-cove-nerd-font
cask font-code-new-roman-nerd-font
cask font-cousine-nerd-font
cask font-daddy-time-mono-nerd-font
cask font-dejavu-sans-mono-nerd-font
cask font-droid-sans-mono-nerd-font
cask font-fantasque-sans-mono-nerd-font
cask font-fira-code-nerd-font
cask font-fira-mono-nerd-font
cask font-fontawesome
cask font-go-mono-nerd-font
cask font-gohufont-nerd-font
cask font-hack-nerd-font
cask font-hackgen-nerd
cask font-hasklug-nerd-font
cask font-heavy-data-nerd-font
cask font-hurmit-nerd-font
cask font-im-writing-nerd-font
cask font-inconsolata-go-nerd-font
cask font-inconsolata-lgc-nerd-font
cask font-inconsolata-nerd-font
cask font-iosevka-nerd-font
cask font-jetbrains-mono
cask font-jetbrains-mono-nerd-font
cask font-lekton-nerd-font
cask font-liberation-nerd-font
cask font-meslo-lg-nerd-font
cask font-monofur-nerd-font
cask font-monoid-nerd-font
cask font-mononoki-nerd-font
cask font-mplus-nerd-font
cask font-noto-nerd-font
cask font-open-dyslexic-nerd-font
cask font-overpass-nerd-font
cask font-profont-nerd-font
cask font-proggy-clean-tt-nerd-font
cask font-roboto-mono-nerd-font
cask font-sauce-code-pro-nerd-font
cask font-shure-tech-mono-nerd-font
cask font-space-mono-nerd-font
cask font-terminess-ttf-nerd-font
cask font-tinos-nerd-font
cask font-ubuntu-mono-nerd-font
cask font-ubuntu-nerd-font
cask font-victor-mono-nerd-font

tap homebrew/cask-versions
cask adoptopenjdk8

tap homebrew/services

tap homebrew/cask
cask 1password
cask adium
cask aerial
cask airtool
cask alfred
cask anki
cask appcleaner
cask artpip
cask atom
cask balenaetcher
cask bitbar
cask brooklyn
cask calibre
cask cheatsheet
cask clean-me
cask commander-one
cask cryptomator
cask cyberduck
cask dash
cask dbeaver-community
cask deepl
cask developerexcuses
cask discord
cask docker
cask dropbox
cask duet
cask epoch-flip-clock
cask firefox
cask flash-player
cask fliqlo
cask flux
cask gitify
cask go64
cask gpg-suite
cask hiddenbar
cask iina
cask insomnia
cask iterm2
cask java
cask jetbrains-toolbox
cask karabiner-elements
cask keybase
cask kindle
cask launchcontrol
cask little-snitch
cask marta
cask media-converter
cask micro-snitch
cask netspot
cask notion
cask pocket-casts
cask podman
cask punto-switcher
cask rocket
cask rq
cask send-to-kindle
cask signal
cask slack
cask spectacle
cask spotify
cask telegram-desktop
cask the-unarchiver
cask transmission
cask tunnelblick
cask tutanota
cask vagrant
cask virtualbox
cask visual-studio-code
cask vlc
cask whatsapp
cask wifi-explorer
cask wire
cask wireshark
cask xnviewmp
cask zerotier-one

tap alehouse/unofficial

tap cjbassi/gotop

tap cristianoliveira/tap
brew funzzy

## Direct install
brew sshpass

tap getantibody/tap

tap homebrew-ffmpeg/ffmpeg

tap hudochenkov/sshpass

tap jesseduffield/lazygit

tap jzelinskie/faq
brew faq

tap minio/stable

tap pokanop/pokanop
brew nostromo

tap rcmdnk/file
brew brew-file

tap rigellute/tap

tap rs/tap
brew curlie

tap sambadevi/powerlevel9k

tap schollz/tap
brew croc

tap sidaf/pentest

tap timothyye/tap
brew skm

tap warrensbox/tap
brew tfswitch

tap zero-sh/tap
brew apply-user-defaults
brew zero

# Other Cask applications
cask font-3270-nerd-font-mono
cask font-anonymouspro-nerd-font
cask font-anonymouspro-nerd-font-mono
cask font-arimo-nerd-font-mono
cask font-aurulentsansmono-nerd-font
cask font-aurulentsansmono-nerd-font-mono
cask font-bitstreamverasansmono-nerd-font
cask font-bitstreamverasansmono-nerd-font-mono
cask font-cascadia-nerd-font
cask font-cascadia-nerd-font-mono
cask font-codenewroman-nerd-font
cask font-codenewroman-nerd-font-mono
cask font-cousine-nerd-font-mono
cask font-dejavusansmono-nerd-font
cask font-dejavusansmono-nerd-font-mono
cask font-droidsansmono-nerd-font
cask font-droidsansmono-nerd-font-mono
cask font-fantasquesansmono-nerd-font
cask font-fantasquesansmono-nerd-font-mono
cask font-firacode-nerd-font
cask font-firacode-nerd-font-mono
cask font-firamono-nerd-font
cask font-firamono-nerd-font-mono
cask font-go-mono-nerd-font-mono
cask font-gohu-nerd-font
cask font-gohu-nerd-font-mono
cask font-hack-nerd-font-mono
cask font-hasklig-nerd-font
cask font-hasklig-nerd-font-mono
cask font-heavydata-nerd-font
cask font-heavydata-nerd-font-mono
cask font-hermit-nerd-font
cask font-hermit-nerd-font-mono
cask font-inconsolata-nerd-font-mono
cask font-inconsolatago-nerd-font
cask font-inconsolatago-nerd-font-mono
cask font-inconsolatalgc-nerd-font
cask font-inconsolatalgc-nerd-font-mono
cask font-iosevka-nerd-font-mono
cask font-jetbrainsmono-nerd-font
cask font-lekton-nerd-font-mono
cask font-liberationmono-nerd-font
cask font-liberationmono-nerd-font-mono
cask font-meslo-nerd-font
cask font-meslo-nerd-font-mono
cask font-monofur-nerd-font-mono
cask font-monoid-nerd-font-mono
cask font-mononoki-nerd-font-mono
cask font-mplus-1mn-nerd-mono
cask font-mplus-nerd-font-mono
cask font-noto-nerd-font-mono
cask font-profont-nerd-font-mono
cask font-proggyclean-nerd-font
cask font-proggyclean-nerd-font-mono
cask font-robotomono-nerd-font
cask font-robotomono-nerd-font-mono
cask font-sharetechmono-nerd-font
cask font-sharetechmono-nerd-font-mono
cask font-sourcecodepro-nerd-font
cask font-sourcecodepro-nerd-font-mono
cask font-spacemono-nerd-font
cask font-spacemono-nerd-font-mono
cask font-terminus-nerd-font
cask font-terminus-nerd-font-mono
cask font-tinos-nerd-font-mono
cask font-ubuntu-nerd-font-mono
cask font-ubuntumono-nerd-font
cask font-ubuntumono-nerd-font-mono

# App Store applications
appstore 1480070821 Cyph (1.0.73)
appstore 924726344 Deliveries (3.2.3)
appstore 975937182 Fantastical (3.1.4)
appstore 409183694 Keynote (10.1)
appstore 1464122853 NextDNS (1.4.3)
appstore 409203825 Numbers (10.1)
appstore 409201541 Pages (10.1)
appstore 1449412482 Reeder (4.2.5)
appstore 904280696 Things (3.12.6)
appstore 557168941 Tweetbot (2.5.8)
appstore 1482454543 Twitter (8.31)
appstore 447521961 XChat Azure (1.18.11)
